### ISSUE TITLE
Support new version of joi.

### ISSUE THREAD

**Issue by mkovel** [feathersjs-ecosystem/validate-joi#27]
Hi guys.
@marshallswain @EdwardDrapkin @adamvr @eddyystop @claustres 
As you know **joi** divorced with **hapi** and a new version of **joi** is not compatible with the current version of **validate-joi**.
Do you have plans to migrate to the latest version of **joi**? if you are busy I can do it. ;)

**Comment by marshallswain** [comment]
That would be wonderful to make the switch. We can do it as a new major version number.  If you have the time to make the PR that would be very much appreciated.
